requirejs.config({
    "urlArgs": "bust=" + (new Date()).getTime(),
    "paths":{
        "react":'../bower_components/react/react',
        "bootstrap":'../bower_components/bootstrap/dist/js/bootstrap',
        "jquery":"../bower_components/jquery/dist/jquery.min",
        "Jquery-Conflict":'src/jquery-conflict',
        "MapEditor":'../core/Tools/build/MapEditor',
        "CE":'../bower_components/CanvasEngine/src/core/CanvasEngine',
        "Map":'../bower_components/CanvasEngine/src/core/Map',
        "Grid":'../bower_components/CanvasEngine/src/core/Grid',
        "ImageLoader":'../core/Resources/ImageLoader',
        "InputNumber":'../bower_components/ReactElements/build/InputNumber',
        "Math":'../bower_components/MathLib/build/Math',
        "AbstractGrid":'../bower_components/CanvasEngine/src/core/AbstractGrid',
        "ImageSet":'../bower_components/CanvasEngine/src/core/ImageSet',
        "CanvasLayer":'../bower_components/CanvasEngine/src/core/CanvasLayer',
        "SetIntervalMixin":'../bower_components/ReactElements/build/mixins/setIntervalMixin',
        "PropsParser":'../custom/PropsParser' ,
        "MouseReader":'../core/Reader/MouseReader',
        "RectSet":'../bower_components/CanvasEngine/src/core/RectSet',
        "Overlap":'../bower_components/MathLib/build/Overlap',
        "Color":'../core/Graphics/Color',
        "ObjectLayer":"../bower_components/CanvasEngine/src/core/ObjectLayer"
    },
    "shim":{
        "bootstrap":{
            deps:["jquery"]
        },
        "InputNumber":{
            deps:['SetIntervalMixin']
        },
        "ObjectLayer":{
            deps:["CanvasLayer"]
        }
    }
});