requirejs.config({
    "paths":{
        "jquery":"../../../bower_components/jquery/dist/jquery.min",
        "CE":"../../Graphics/CanvasEngine",
        "CanvasLayer":"../../Graphics/CanvasLayer",
        "PropsParser":"../../../custom/PropsParser",
        "ImageSet":"../../Graphics/ImageSet",
        "RL":"../../Resources/ResourcesLoader",
        "ImageLoader":"../../Resources/ImageLoader",
        "FrameSync":'../../Graphics/FrameSync'
    }
});